export default {
    FONT: "#303d49",
    FONT_MEDIUM: "#636363",
    FONT_LIGHT: "#b6b8b9",
    MODAL_BG: "rgba(0,0,0,0.5)",
    ACTIVE_BG: "#5252ad",
    ACTIVE_FONT: "#fff",
    APP_BG: '#fff',
    APP_TEXT: '#000',
    APP_THEME: '#000',
    APP_BTN_BG: '#000',
    APP_BTN_TXT: '#fff',
    APP_ICON: '#000',
    APP_BORDER: '#ccc',
    APP_INPUT: '#f2f2f2',
    APP_HEADER: '#000',
    APP_ACTIVE: '#000',
    APP_PLACEHOLDER: '#ccc',
    APP_SHADOW: '#000',
    APP_DANGER: '#ff0000',
    APP_WARNING: '#ffcc00',
    APP_SUCCESS: '#00ff00',
    APP_INFO: '#0099ff',
    APP_INACTIVE: '#ccc',
    APP_SLIDER: '#000',
    APP_DISABLED: '#ccc',
}